### ISSUE TITLE
Back button keeps previous search parameters

### ISSUE THREAD

**Issue by wolfenmark** [seart-group/ghs#10]
Hi,
I was wondering if it's possible to keep the search parameters after returning from a search ('Back' button).

Example use case:
 - Set some filtering criteria
 - Search
 - Get results
 - Want to refine/fine-tune/adjust search criteria
 - hit the back button
 - modify criteria I want to adjust (others are "saved/restored" automatically)

Maybe can be also done by supporting the browser's back button (actually ignoring 'in site' navigation) and removing the custom one.

**Comment by emadpres** [comment]
Thanks for the feedback.
I totally agree on how useful this feature is and we are eager to support a proper back mechanism. Said that, the current implementation of the frontend does not allow us to easily implement such a feature (as far as I'm aware, but you are more than welcome to have a look at the source code as well). Rest assured, it will be implemented sooner than later.

**Comment by dabico** [comment]
Actually, it was not as difficult as previously considered. Taking a closer look at the code, I noticed that the form was being cleared explicitly whenever the user navigated back from a search.

https://github.com/seart-group/ghs/blob/ece339898f088efbd015e574dc3daf703f571794/src/main/fe-src/js/retrieve.js#L382-L386

Looking back, I think I added this because a reset button did not fit anywhere in the form, but I completely forgot that a user can just... Refresh the page... 🤦 

Anyway, as of [8fdabdc](https://github.com/dabico/ghs/tree/8fdabdc138bf502dfdc06a34ef06dacd0dd0846d), the back button no longer resets the form.
