### ISSUE TITLE
Number of contributors overreported 

### ISSUE THREAD

**Issue by jhs507** [seart-group/ghs#31]
I recently pulled some data and noticed that there were a few projects that had a reported number of contributors that is quite odd. 

I noticed this for three projects in the data set I am using. The projects in question are:
radeonopencompute/rock-kernel-driver
youling257/android-mainline
xanmod/linux

In the csv output generated the number of contributors for these projects is 9.22337203685477E+018. Or at least it is after I import it to a spreadsheet. 

On the website search results the number of contributors for these projects is 9223372036854776000. 

Based on the number it looks like this is a JavaScript error causing the maximum integer value to be displayed. Obviously the number of contributors to the projects in question cannot be close to these reported values.

**Comment by gbavota** [comment]
Thanks for reporting. I confirm the bug. @dabico Can you have a look please?

**Comment by dabico** [comment]
The cause for the overreporting was due to the fact that we did not properly handle cases when the [GitHub API could not calculate](https://api.github.com/repos/xanmod/linux/contributors) the exact values of specific metrics. Such cases are now properly represented as not available (i.e. "N/A") and are omitted from the export.
